NetCasbin/CoreEnforcer.cs, NetCasbin/NetCasbin.csproj, NetCasbin/Persist/IWatcher.cs
Update the IWatcher interface to be able to use it.
Uncomment the use of the interface IWatcher.
=> Add watcher support

NetCasbin/NetCasbin.csproj
=> removed x64 platform lock-in

.travis.yml, Casbin.NET.sln, README.md
=> Remove travis CI support

README.md
=> Add the Azure Pipeline badge at README.md

NetCasbin.UnitTest/BuiltInOperatorTest.cs, NetCasbin.UnitTest/EnforcerUnitTest.cs, NetCasbin.UnitTest/GroupRoleManagerTest.cs, NetCasbin.UnitTest/ManagementAPIUnitTest.cs, NetCasbin.UnitTest/ModelTest.cs, NetCasbin.UnitTest/RbacAPITest.cs, NetCasbin.UnitTest/RbacAPIWithDomainsTest.cs, NetCasbin.UnitTest/TestUtil.cs, NetCasbin.UnitTest/UtilsTest.cs, NetCasbin/CoreEnforcer.cs, NetCasbin/Enforcer.cs, NetCasbin/InternalEnforcer.cs, NetCasbin/ManagementEnforcer.cs, NetCasbin/Persist/FileAdapter/DefaultFileAdapter.cs, NetCasbin/Persist/FileAdapter/DefaultFilteredAdapter.cs, NetCasbin/Persist/IAdapter.cs, NetCasbin/Persist/IFilteredAdapter.cs, NetCasbin/Persist/IWatcher.cs
=>  Add async support

NetCasbin/Model/Assertion.cs, NetCasbin/Model/Model.cs, NetCasbin/Model/Policy.cs, NetCasbin/Persist/FileAdapter/DefaultFileAdapter.cs, NetCasbin/Util/Utility.cs
=> Merge the manage policy steps to one

.gitignore, NetCasbin/Config/Config.cs, NetCasbin/CoreEnforcer.cs, NetCasbin/Effect/IEffector.cs, NetCasbin/Enforcer.cs, NetCasbin/InternalEnforcer.cs, NetCasbin/ManagementEnforcer.cs, NetCasbin/Model/Model.cs, NetCasbin/Rbac/GroupRoleManager.cs, NetCasbin/Rbac/IRoleManager.cs, NetCasbin/Util/BuiltInFunctions.cs, NetCasbin/Util/Utility.cs
It fixed typos at `ManagementEnforcer.cs` and completed and standardized the comments
=> Fix typos and complete and standardize the comments

NetCasbin/Rbac/IRoleManager.cs, NetCasbin/Util/BuiltInFunctions.cs
It will remove all Chinese comments and standardize some comments.
=> Remove all Chinese comments and standardize some comments

NetCasbin/Config/Config.cs, NetCasbin/CoreEnforcer.cs, NetCasbin/Effect/DefaultEffector.cs, NetCasbin/Enforcer.cs, NetCasbin/ManagementEnforcer.cs, NetCasbin/Model/Model.cs, NetCasbin/Model/PermConstants.cs, NetCasbin/Model/Policy.cs, NetCasbin/Persist/FileAdapter/DefaultFileAdapter.cs, NetCasbin/Persist/FileAdapter/DefaultFilteredAdapter.cs, NetCasbin/Util/Utility.cs
=> Replace repeated strings to constant

NetCasbin.UnitTest/EnforcerUnitTest.cs, NetCasbin.UnitTest/Fixtures/TestModelFixture.cs, NetCasbin.UnitTest/GroupRoleManagerTest.cs, NetCasbin.UnitTest/ManagementAPIUnitTest.cs, NetCasbin.UnitTest/ModelTest.cs, NetCasbin.UnitTest/RbacAPITest.cs, NetCasbin.UnitTest/RbacAPIWithDomainsTest.cs, NetCasbin.UnitTest/Util/TestUtil.cs, NetCasbin.UnitTest/UtilityTest.cs
=>  Fix the IO exception when sometimes running unit tests

NetCasbin.UnitTest/ManagementAPIUnitTest.cs, NetCasbin/Model/Policy.cs
=> Change the filter workflow at model

NetCasbin.UnitTest/BuiltInOperatorTest.cs, NetCasbin/Abstractions/AbstractFunction.cs, NetCasbin/Model/FunctionMap.cs, NetCasbin/Util/AviatorFunction.cs, NetCasbin/Util/BuiltInFunctions.cs, NetCasbin/Util/Function/IPMatchFunc.cs, NetCasbin/Util/Function/KeyMatch2Func.cs, NetCasbin/Util/Function/KeyMatch4Func.cs, NetCasbin/Util/Function/KeyMatchFunc.cs
=> Add KeyMatch4 function support

.github/workflows/github-actions.yml, Casbin.Benchmark/EnforcerBenchmark.cs, Casbin.Benchmark/ModelBenchmark.cs, Casbin.NET.sln
=> Run benchmark on Github Actions

.github/workflows/github-actions-benchmark.yml, .github/workflows/github-actions-release.yml, Casbin.Benchmark/Casbin.Benchmark.csproj, Casbin.NET.sln
=> Auto release github packages on Github Actions

NetCasbin.UnitTest/Fixtures/TestModelFixture.cs, NetCasbin.UnitTest/NetCasbin.UnitTest.csproj, NetCasbin.UnitTest/WatcherTest.cs, NetCasbin/CoreEnforcer.cs
=> Add watcher unit test

NetCasbin.UnitTest/EnforcerUnitTest.cs, NetCasbin.UnitTest/Fixtures/TestModelFixture.cs, NetCasbin.UnitTest/ModelTest.cs, NetCasbin/CoreEnforcer.cs, NetCasbin/Model/Model.cs, NetCasbin/Model/PermConstants.cs, NetCasbin/Util/Utility.cs
=> Change the workflow of creating a model

.github/workflows/github-actions-benchmark.yml, NetCasbin.UnitTest/Fixtures/TestModelFixture.cs, NetCasbin.UnitTest/ModelTest.cs, NetCasbin.UnitTest/NetCasbin.UnitTest.csproj, NetCasbin.UnitTest/Util/TestUtil.cs, NetCasbin.UnitTest/examples/abac_rule_model.conf, NetCasbin.UnitTest/examples/abac_rule_policy.csv, NetCasbin/Abstractions/IExpresstionCreator.cs, NetCasbin/CoreEnforcer.cs, NetCasbin/Enforcer.cs, NetCasbin/Evaluation/IExpressionProvider.cs, NetCasbin/ManagementEnforcer.cs, NetCasbin/Model/Assertion.cs, NetCasbin/Model/Model.cs, NetCasbin/NetCasbin.csproj, NetCasbin/Util/Utility.cs
=> Support eval function and improve performance of enforcing

NetCasbin.UnitTest/Collections/ModelCollection.cs, NetCasbin.UnitTest/ManagementApiTest.cs, NetCasbin.UnitTest/ModelTest.cs, NetCasbin.UnitTest/RbacAPITest.cs, NetCasbin.UnitTest/RbacAPIWithDomainsTest.cs, NetCasbin.UnitTest/WatcherTest.cs, NetCasbin/CoreEnforcer.cs, NetCasbin/InternalEnforcer.cs, NetCasbin/ManagementEnforcer.cs
=> Support auto notify watcher option and clean up the internal enforcer

Casbin.Benchmark/BuildInFunctionsBenchmark.cs, NetCasbin.UnitTest/BuiltInFunctionTest.cs, NetCasbin/Extensions/IPAddressExtension.cs, NetCasbin/Util/BuiltInFunctions.cs
=> Support IPv6 on IPMatch function

NetCasbin.UnitTest/EnforcerUnitTest.cs, NetCasbin.UnitTest/ModelTest.cs, NetCasbin.UnitTest/RbacApiTest.cs, NetCasbin.UnitTest/Util/TestUtil.cs, NetCasbin/CoreEnforcer.cs
=> Support async enforce method

.github/workflows/github-actions-release.yml, NetCasbin.UnitTest/EnforcerUnitTest.cs, NetCasbin.UnitTest/Fixtures/TestModelFixture.cs, NetCasbin/Model/Model.cs, NetCasbin/NetCasbin.csproj
Change the release note and clean up the project properties.
=> Release v1.4.0 version

.github/workflows/github-actions-benchmark.yml, .github/workflows/github-actions-build.yml, .github/workflows/github-actions-release.yml, Casbin.Benchmark/BuildInFunctionsBenchmark.cs, Casbin.Benchmark/Casbin.Benchmark.csproj, Casbin.Benchmark/EnforcerBenchmark.cs, Casbin.Benchmark/ModelBenchmark.cs, azure-pipelines.yml
=> Add .NET 5 target benchmark

NetCasbin.UnitTest/Fixtures/TestModelFixture.cs, NetCasbin.UnitTest/RbacApiTest.cs, NetCasbin/Enforcer.cs, NetCasbin/Model/Policy.cs
=> Add GetImplicitUsersForPermission API

NetCasbin.UnitTest/UtilityTest.cs, NetCasbin/CoreEnforcer.cs, NetCasbin/Util/Utility.cs
=> Support multiple eval functions

NetCasbin/CoreEnforcer.cs
=> Fix determine filter adapter error when loading filter policy

.github/workflows/github-actions-benchmark.yml, .github/workflows/github-actions-build.yml, .github/workflows/github-actions-release.yml, NetCasbin.UnitTest/Fixtures/TestModelFixture.cs, NetCasbin.UnitTest/NetCasbin.UnitTest.csproj, NetCasbin.UnitTest/RbacApiTest.cs, NetCasbin.UnitTest/Util/TestUtil.cs, NetCasbin.UnitTest/examples/rbac_with_hierarchy_with_domains_policy.csv, NetCasbin/Abstractions/IEnforcer.cs, NetCasbin/CoreEnforcer.cs, NetCasbin/Enforcer.cs, azure-pipelines.yml
=> Add domain optional support at RBAC APIs

NetCasbin.UnitTest/Mock/MockRoleManager.cs, NetCasbin.UnitTest/ModelTest.cs, NetCasbin.UnitTest/NetCasbin.UnitTest.csproj, NetCasbin.UnitTest/RoleManagerTest.cs, NetCasbin.UnitTest/Util/TestUtil.cs, NetCasbin/Extensions/RoleMangerExtension.cs, NetCasbin/Rbac/DefaultRoleManager.cs, NetCasbin/Rbac/GroupRoleManager.cs, NetCasbin/Rbac/IRoleManager.cs, NetCasbin/Rbac/Role.cs, NetCasbin/ThrowHelper.cs
=> Support pattern feature at default role manager

NetCasbin/Model/Assertion.cs, NetCasbin/Model/Model.cs
Fix: https://github.com/casbin/Casbin.NET/issues/79
=> fix: Make assertion properties to read-only for public

Casbin.Benchmark/EnforcerBenchmark.cs, NetCasbin.UnitTest/EnforcerTest.cs, NetCasbin.UnitTest/Mock/MockLogger.cs, NetCasbin.UnitTest/NetCasbin.UnitTest.csproj, NetCasbin.UnitTest/Util/TestUtil.cs, NetCasbin/Abstractions/IChainEffector.cs, NetCasbin/CoreEnforcer.cs, NetCasbin/Effect/DefaultEffector.cs, NetCasbin/Effect/IEffector.cs, NetCasbin/Enforcer.cs, NetCasbin/Evaluation/EffiectEvaluation.cs, NetCasbin/Extensions/LoggerExtension.cs, NetCasbin/Model/Policy.cs, NetCasbin/NetCasbin.csproj
close #116  and close #109, the IEffector interface is changed.
=> Support logging feature and add EnforceEx method

NetCasbin.UnitTest/EnforcerTest.cs, NetCasbin.UnitTest/Fixtures/TestModelFixture.cs, NetCasbin/Abstractions/IConfig.cs, NetCasbin/Abstractions/IEnforcer.cs, NetCasbin/Abstractions/IModel.cs, NetCasbin/Abstractions/IPolicy.cs, NetCasbin/Adapter/File/FileAdapter.cs, NetCasbin/Adapter/File/FileFilteredAdapter.cs, NetCasbin/Config/Config.cs, NetCasbin/Enforcer.cs, NetCasbin/Evaluation/ExpressionHandler.cs, NetCasbin/Extensions/RbacEnforcerEnxtension.cs, NetCasbin/Model/Assertion.cs, NetCasbin/Model/DefaultModel.cs, NetCasbin/Model/DefaultPolicy.cs, NetCasbin/Persist/Helper.cs, NetCasbin/Persist/IAdapter.cs, NetCasbin/Persist/IFilteredAdapter.cs
=> refactor: Improve the extendibility structure

Casbin.Benchmark/EnforcerWithCacheBenchmark.cs, NetCasbin.UnitTest/EnforcerCacheTest.cs, NetCasbin.UnitTest/EnforcerTest.cs, NetCasbin.UnitTest/ManagementApiTest.cs, NetCasbin.UnitTest/Mock/MockLogger.cs, NetCasbin.UnitTest/NetCasbin.UnitTest.csproj, NetCasbin.UnitTest/RbacApiTest.cs, NetCasbin.UnitTest/Util/TestUtil.cs, NetCasbin/Abstractions/IEnforceCache.cs, NetCasbin/Caching/ConcurrentEnforceCache.cs, NetCasbin/Caching/ReaderWriterEnforceCache.cs, NetCasbin/Caching/ReaderWriterEnforceCacheOptions.cs, NetCasbin/CoreEnforcer.cs, NetCasbin/Extensions/LoggerExtension.cs, NetCasbin/InternalEnforcer.cs
Fix: https://github.com/casbin/Casbin.NET/issues/142
=> feat: Support caching feature

NetCasbin.UnitTest/GroupRoleManagerTest.cs, NetCasbin/CoreEnforcer.cs, NetCasbin/Enforcer.cs, NetCasbin/Extensions/EnforcerExtension.cs, NetCasbin/Extensions/ModelExtension.cs, NetCasbin/InternalEnforcer.cs, NetCasbin/Model/Assertion.cs, NetCasbin/Model/Policy.cs
=> feat: Support multiple role manager

NetCasbin.UnitTest/EnforcerTest.cs, NetCasbin/ManagementEnforcer.cs, NetCasbin/Model/Model.cs
Fix: https://github.com/casbin/Casbin.NET/issues/157
Fix: https://github.com/casbin/Casbin.NET/issues/158
=> fix: Add lacked API AddNamedGroupingPolicyAsync

NetCasbin.UnitTest/EnforcerTest.cs, NetCasbin.UnitTest/Fixtures/TestModelFixture.cs, NetCasbin.UnitTest/examples/rbac_multiple_rolemanager_model.conf, NetCasbin.UnitTest/examples/rbac_multiple_rolemanager_policy.csv, NetCasbin/CoreEnforcer.cs, NetCasbin/Rbac/DefaultRoleManager.cs, NetCasbin/Rbac/Role.cs
=> fix: Fix error result of HasLink method and improve role manager performence

NetCasbin.UnitTest/EnforcerTest.cs, NetCasbin.UnitTest/Fixtures/TestModelFixture.cs, NetCasbin.UnitTest/NetCasbin.UnitTest.csproj, NetCasbin.UnitTest/examples/rbac_multiple_eval_model.conf, NetCasbin.UnitTest/examples/rbac_multiple_eval_policy.csv, NetCasbin/Util/Utility.cs
=> fix: Unable replace multiple eval

.github/workflows/build.yml, .github/workflows/release.yml, Casbin.Benchmark/BuildInFunctionsBenchmark.cs, Casbin.Benchmark/Casbin.Benchmark.csproj, Casbin.Benchmark/EnforcerBenchmark.cs, Casbin.Benchmark/EnforcerWithCacheBenchmark.cs, Casbin.Benchmark/ModelBenchmark.cs, Casbin.Benchmark/Program.cs, NetCasbin.UnitTest/NetCasbin.UnitTest.csproj, NetCasbin/NetCasbin.csproj, azure-pipelines.yml
=> feat: Support .NET 6 target

NetCasbin.UnitTest/Fixtures/TestModelFixture.cs, NetCasbin.UnitTest/ModelTest.cs, NetCasbin.UnitTest/NetCasbin.UnitTest.csproj, NetCasbin.UnitTest/examples/priority_explicit_model.conf, NetCasbin.UnitTest/examples/priority_explicit_policy.csv, NetCasbin/CoreEnforcer.cs, NetCasbin/Model/Assertion.cs, NetCasbin/Model/Policy.cs
=> feat: Support explicit priority model

NetCasbin.UnitTest/EnforcerTest.cs, NetCasbin.UnitTest/Util/TestUtil.cs, NetCasbin/CoreEnforcer.cs
=> feat: Add EnforceWithMatcher and EnforceExWithMatcher APIs

NetCasbin.UnitTest/ModelTests/EnforcerTest.cs, NetCasbin/DefaultEnforcer.cs, NetCasbin/Enforcer.cs
=> feat: Add lazyLoadPolicy option on enforcer constructor

NetCasbin/Abstractions/IEnforcer.cs, NetCasbin/Abstractions/IExpressionHandler.cs, NetCasbin/Abstractions/IPolicy.cs, NetCasbin/EnforceContext.cs, NetCasbin/Enforcer.cs, NetCasbin/Evaluation/ExpressionHandler.cs, NetCasbin/Extensions/Enforcer/EnforcerExtension.cs, NetCasbin/Extensions/ModelExtension.cs, NetCasbin/Model/Assertion.cs, NetCasbin/Model/DefaultModel.cs, NetCasbin/Model/DefaultPolicy.cs
Fix: #186 
**Draft** Need to observe performance changes.
=> refactor: Reduce duplicate code of Enforce APIs

NetCasbin.UnitTest/Casbin.UnitTests.csproj, NetCasbin.UnitTest/Fixtures/TestModelFixture.cs, NetCasbin.UnitTest/ModelTests/ModelTest.cs, NetCasbin.UnitTest/examples/priority_explicit_deny_override_model.conf, NetCasbin.UnitTest/examples/priority_explicit_deny_override_policy.csv, NetCasbin/Abstractions/Effect/IChainEffector.cs, NetCasbin/Abstractions/Evaluation/IExpressionHandler.cs, NetCasbin/Abstractions/IEnforcer.cs, NetCasbin/Effect/DefaultEffector.cs, NetCasbin/Effect/EffectExpressionType.cs, NetCasbin/EnforceContext.cs, NetCasbin/EnforceSession.cs, NetCasbin/Enforcer.cs, NetCasbin/Evaluation/EffiectEvaluation.cs, NetCasbin/Evaluation/ExpressionHandler.cs, NetCasbin/PermConstants.cs, NetCasbin/ThrowHelper.cs
Fixes: #199
Draft: observing performance
=> feat: Implement priority explicit deny override model for v2

NetCasbin.UnitTest/EnforcerTest.cs, NetCasbin.UnitTest/Fixtures/TestModelFixture.cs, NetCasbin.UnitTest/Mock/MockRoleManager.cs, NetCasbin.UnitTest/ModelTest.cs, NetCasbin.UnitTest/NetCasbin.UnitTest.csproj, NetCasbin.UnitTest/RoleManagerTest.cs, NetCasbin.UnitTest/examples/rbac_with_domains_pattern_model.conf, NetCasbin.UnitTest/examples/rbac_with_domains_pattern_policy.csv, NetCasbin/Model/Assertion.cs, NetCasbin/NetCasbin.csproj, NetCasbin/Rbac/DefaultRoleManager.cs, NetCasbin/Rbac/IRoleManager.cs, NetCasbin/Rbac/Role.cs, NetCasbin/Util/BuiltInFunctions.cs
=> fix: Error return on HasLink when has matching in Inheritance chain

.github/workflows/build.yml, .github/workflows/release.yml, Casbin.Benchmark/Casbin.Benchmark.csproj, NetCasbin.UnitTest/Casbin.UnitTests.csproj, NetCasbin/Casbin.csproj, azure-pipelines.yml
=> chore: Update to C# 10.0 version

NetCasbin/Abstractions/IEnforcer.cs, NetCasbin/Caching/ConcurrentEnforceCache.cs, NetCasbin/Caching/ReaderWriterEnforceCache.cs, NetCasbin/Casbin.csproj, NetCasbin/Enforcer.cs, NetCasbin/Extensions/Enforcer/EnforcerExtension.cs, NetCasbin/Extensions/Enforcer/InternalEnforcerExtension.cs, NetCasbin/Extensions/LoggerExtension.cs, NetCasbin/Model/DefaultPolicy.cs
Fix #168, wait for the discussion result.
Fix: https://github.com/casbin/Casbin.NET/issues/168
=> fix: Change lowest TFM form net45 to net452

.github/workflows/build.yml, .github/workflows/release.yml, NetCasbin/Abstractions/Caching/IEnforceViewCache.cs, NetCasbin/Abstractions/IEnforcer.cs, NetCasbin/Abstractions/Model/IModel.cs, NetCasbin/Caching/EnforceViewCache.cs, NetCasbin/Casbin.csproj, NetCasbin/EnforceContext.cs, NetCasbin/EnforceSession.cs, NetCasbin/EnforceView.cs, NetCasbin/Enforcer.cs, NetCasbin/Evaluation/ExpressionHandler.cs, NetCasbin/Extensions/Enforcer/EnforcerExtension.cs, NetCasbin/Extensions/Enforcer/InternalEnforcerExtension.cs, NetCasbin/Extensions/Enforcer/ManagementEnforcerExtension.cs, NetCasbin/Extensions/Model/ModelExtension.cs, NetCasbin/Model/DefaultModel.cs
=> feat: Reading cache before create context and cache the model parse reuslt

NetCasbin/Model/Policy.cs, NetCasbin/Persist/FileAdapter/DefaultFileAdapter.cs, NetCasbin/Persist/Helper.cs
=> fix: Add tryLoadPolicy line to support comma tokens for some adapter

NetCasbin/Extensions/EnforcerExtension.cs
=> fix: Error func call at AddNamedDomainMatchingFunc at enforcer extension

Casbin/Abstractions/Evaluation/IExpressionHandler.cs, Casbin/Caching/ExpressionCache.cs, Casbin/Caching/ExpressionCachePool.cs, Casbin/Casbin.csproj, Casbin/Evaluation/ExpressionHandler.cs, Casbin/Util/Utility.cs
=> fix: Make expression cache thread safe

Casbin.Benchmark/ModelBenchmark.cs
Test: Add new benchmarks for management APIs referring to Go version
=> test: Add new benchmarks for management APIs

Casbin.UnitTest/ModelTests/ManagementApiTest.cs, Casbin.UnitTest/Util/TestUtil.cs
Test: Add new unittests to ManagementApi referring to Go version.
=> test: Add new unit tests for management APIs

Casbin.UnitTest/ModelTests/ManagementApiTest.cs, Casbin.UnitTest/SyncedModelTests/SyncedManagementApiTest.cs, Casbin/Abstractions/Model/IPolicyManager.cs, Casbin/Abstractions/Model/IPolicyStore.cs, Casbin/Abstractions/Model/IPolicyValues.cs, Casbin/Abstractions/Persist/IBatchAdapter.cs, Casbin/Abstractions/Persist/ISingleAdapter.cs, Casbin/Adapter/File/FileAdapter.cs, Casbin/Extensions/Enforcer/InternalEnforcerExtension.cs, Casbin/Extensions/Enforcer/ManagementEnforcerExtension.cs, Casbin/Extensions/Persist/PolicyStoreExtension.cs, Casbin/Model/Assertion.cs, Casbin/Model/DefaultModel.cs, Casbin/Model/DefaultPolicyManager.cs, Casbin/Model/DefaultPolicyStore.cs, Casbin/Model/Policy.cs, Casbin/Model/ReaderWriterPolicyManager.cs, Casbin/Persist/Filter.cs, Casbin/PolicyOperation.cs, Casbin/Util/Utility.cs
=> feat: Store policy text in the policy values instance

Casbin/Abstractions/Model/IModel.cs, Casbin/Abstractions/Model/IPolicyManager.cs, Casbin/Abstractions/Model/IPolicyStore.cs, Casbin/Abstractions/Persist/IBatchAdapter.cs, Casbin/Abstractions/Persist/ISingleAdapter.cs, Casbin/Extensions/Enforcer/InternalEnforcerExtension.cs, Casbin/Extensions/Enforcer/ManagementEnforcerExtension.cs, Casbin/Model/DefaultModel.cs, Casbin/Model/DefaultPolicyManager.cs, Casbin/Model/DefaultPolicyStore.cs, Casbin/Model/Policy.cs, Casbin/Model/ReaderWriterPolicyManager.cs
feat: Use PolicyValues at models instead of IEnumerable
=> feat: Use PolicyValues at models instead of IEnumerable

Casbin.UnitTests/UtilTests/BuiltInFunctionTest.cs, Casbin/Model/FunctionMap.cs, Casbin/Util/BuiltInFunctions.cs
Add keyGet2 and corresponding test.
=> feat: add keyGet2 and corresponding test.

Casbin.UnitTests/Extensions/RequestValuesExtension.cs, Casbin.UnitTests/ParallelTestHelper/DefaultRbacConsumer.cs, Casbin.UnitTests/ParallelTestHelper/EntropyPool/DefaultExistedEntropyPool.cs, Casbin.UnitTests/ParallelTestHelper/EntropyPool/DefaultRandomEntropyPool.cs, Casbin.UnitTests/ParallelTestHelper/EntropyPool/EntropyHandlers.cs, Casbin.UnitTests/ParallelTestHelper/EntropyPool/IEntropyHandler.cs, Casbin.UnitTests/ParallelTestHelper/EntropyPool/IEntropyPool.cs, Casbin.UnitTests/ParallelTestHelper/IConsumer.cs, Casbin.UnitTests/ParallelTestHelper/RandomRequestGenerator.cs, Casbin.UnitTests/ParallelTestHelper/RbacParallelTestHelper.cs, Casbin.UnitTests/ParallelTestHelper/Transaction/DefaultAddPolicyTransaction.cs, Casbin.UnitTests/ParallelTestHelper/Transaction/DefaultGetAccessTransaction.cs, Casbin.UnitTests/ParallelTestHelper/Transaction/DefaultRemovePolicyTransaction.cs, Casbin.UnitTests/ParallelTestHelper/Transaction/DefaultTransactionFactory.cs, Casbin.UnitTests/ParallelTestHelper/Transaction/ITransaction.cs, Casbin.UnitTests/ParallelTestHelper/Transaction/ITransactionFactory.cs, Casbin.UnitTests/ParallelTests/SyncParallelTest.cs
Add automatic parallel test helper.
The design needs further discussion.
=> feat: add automatic parallel test helper.

Casbin.Benchmark/DefaultPolicyManagerBenchmark.cs
Add benchmark for default policy manager. #177 
Fix: https://github.com/casbin/Casbin.NET/issues/177
=> test: Add benchmark for default policy manager.

Casbin.UnitTests/Casbin.UnitTests.csproj, Casbin.UnitTests/Fixtures/TestModelFixture.cs, Casbin.UnitTests/ModelTests/EnforcerTest.cs, Casbin.UnitTests/examples/rbac_in_operator_model.conf, Casbin.UnitTests/examples/rbac_in_operator_policy.csv, Casbin/Casbin.csproj, Casbin/Enforcer.Internal.cs, Casbin/Util/StringUtil.cs
Support in operator in model config. (solve #197)
=> feat: support in operator in model config.

Casbin.Benchmark/Casbin.Benchmark.csproj, Casbin.Benchmark/DefaultRoleManagerBenchmark.cs, Casbin.Benchmark/examples/rbac_with_pattern_large_scale_model.conf, Casbin.Benchmark/examples/rbac_with_pattern_large_scale_policy.csv
Add benchmark test for default role manager.
=> test: Add benchmark test for default role manager.

Casbin.UnitTests/UtilTests/BuiltInFunctionTest.cs, Casbin/Model/FunctionMap.cs, Casbin/Util/BuiltInFunctions.cs
Add ```keyGet3``` and correponding test.
=> feat: add keyGet3 and correponding test.

Casbin.UnitTests/ModelTests/EnforcerTest.cs, Casbin/Adapter/Stream/StreamAdapter.cs, Casbin/Adapter/Stream/StreamFilteredAdapter.cs
Add stream adapter and filtered stream adapter.
=> feat: Add stream adapter.

Casbin/Abstractions/Model/IReadOnlyPolicyStore.cs, Casbin/Model/DefaultPolicyStore.cs
Add ```GetPolicyTypes``` Api of ```IReadOnlyPolicyStore```.
=> feat: add getPolicyTypes Api of IReadOnlyPolicyStore.

Casbin.UnitTests/GenericTests/SupportCountTests.cs, Casbin/Extensions/Enforcer/EnforcerExtension.GenericEnforce.cs, Casbin/Model/Request.cs, Casbin/Model/RequestValues.cs
Fix: https://github.com/casbin/Casbin.NET/issues/302
=> feat: Add list request values

Casbin/Model/PolicyScanner.cs
Fix: https://github.com/casbin/Casbin.NET/issues/306
=> fix: Warning at policy scanner

Casbin.UnitTests/Casbin.UnitTests.csproj, Casbin.UnitTests/Fixtures/TestModelFixture.cs, Casbin.UnitTests/ModelTests/ModelTest.cs, Casbin.UnitTests/examples/comma_quotations_model.conf, Casbin.UnitTests/examples/comma_quotations_policy.csv, Casbin.UnitTests/examples/rbac_multiple_rolemanager_policy.csv, Casbin/Abstractions/Model/IReadOnlyPolicyStore.cs, Casbin/Adapter/File/FileAdapter.cs, Casbin/Adapter/File/FileFilteredAdapter.cs, Casbin/Casbin.csproj, Casbin/Enforcer.cs, Casbin/Extensions/Persist/PolicyStoreExtension.cs, Casbin/Model/Assertion.cs, Casbin/Model/DefaultPolicyStore.Node.cs, Casbin/Model/MatcherAssertion.cs, Casbin/Model/PolicyAssertion.cs, Casbin/Model/PolicyEffectAssertion.cs, Casbin/Model/RequestAssertion.cs, Casbin/Model/RoleAssertion.cs
#310, implement at the master branch.
=> feat: Support full-fledged CSV parser in built-in file adapter

.github/workflows/push.yml, .github/workflows/release.yml
=> ci: Change to auto-release on push

.github/workflows/build.yml, .github/workflows/infersharp.yml
=> ci: add infersharp.yml & fix a unnecessary command

Casbin.UnitTests/ModelTests/EnforcerTest.cs, Casbin/Model/DefaultSections.cs
=> fix: Support custom g type name

.github/workflows/release.yml, Casbin.UnitTests/Casbin.UnitTests.csproj, Casbin/Casbin.csproj
feat: improve workflow and remove outdated dotnet version
=> feat: support automatic semantic-release

Casbin/Abstractions/Model/IPolicyValues.cs, Casbin/Model/PolicyValues.cs, Casbin/Persist/PersistantPolicy.cs
fix: fix bugs in policy equal and persist
=> fix: fix bugs in policy equal and persist

Casbin.UnitTests/Fixtures/TestModelFixture.cs, Casbin.UnitTests/ModelTests/ModelTest.cs, Casbin.UnitTests/examples/abac_with_dynamic_value_type_model.conf, Casbin.UnitTests/examples/abac_with_dynamic_value_type_policy.csv, Casbin/Evaluation/ExpressionHandler.cs
=> feat: support eval with dynamic request value type

Casbin/Model/DefaultModel.cs
=> chore: add model validate method 
