- appveyor.yml
The reason is `Appveyor` will generate a version string like `6-nbbcpari` when pulling request. But the auto-generate  `Assemblyinfo.cs` do not support this format.
If we do not release from `Appveyor` we can just turn off version path to `.csproj` file to fix it.
> Fix appveyor ci build error

- NetCasbin/InternalEnforcer.cs
> Change update policy workflow

- NetCasbin/CoreEnforcer.cs
- NetCasbin/Enforcer.cs
- NetCasbin/Model/Assertion.cs
- NetCasbin/Model/Policy.cs
- NetCasbin/Persist/FileAdapter/DefaultFileAdapter.cs
close #15 
I created a benchmark project and here is a partial result.
``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19645
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-preview.5.20279.10
[Host]     : .NET Core 3.1.2 (CoreCLR 4.700.20.6602, CoreFX 4.700.20.6702), X64 RyuJIT
Job-FLOMDT : .NET Core 3.1.2 (CoreCLR 4.700.20.6602, CoreFX 4.700.20.6702), X64 RyuJIT
IterationCount=3  RunStrategy=Throughput  
```
**Before**
|    Method | Times | PolicyCount |          Mean |          Error |        StdDev |           Min |           Max |        Median |
|---------- |------ |------------ |--------------:|---------------:|--------------:|--------------:|--------------:|--------------:|
| **HasPolicy** |  **1000** |         **500** | …
> Improve performance when using large amount policy

- NetCasbin/CoreEnforcer.cs
- NetCasbin/Enforcer.cs
- NetCasbin/ICoreEnforcer.cs
- NetCasbin/IEnforcer.cs
- NetCasbin/IManagementEnforcer.cs
- NetCasbin/ManagementEnforcer.cs
Make testing for Casbin.NET easier. So you do not need write complex arranges in your unit tests, use a adapter which will change the test to an integration test or wrapping the enforcer. 
- introduce interface for IEnforcer 
- introduce interface for IManagementEnforcer
- introduce interface for ICoreEnforcer
> provide interface of enforcer to make testing easier

- NetCasbin/Abstractions/ICoreEnforcer.cs
- NetCasbin/Abstractions/IEnforcer.cs
- NetCasbin/Abstractions/IManagementEnforcer.cs
- NetCasbin/CoreEnforcer.cs
- NetCasbin/Enforcer.cs
- NetCasbin/ManagementEnforcer.cs
- NetCasbin/NetCasbin.csproj
> Format the interface code and add an obsolete attribute on it

- Casbin.Benchmark/BuildInFunctionsBenchmark.cs
- NetCasbin/Util/BuiltInFunctions.cs
|       Method |        Job |       Runtime |                 key1 |                 key2 |     Mean |    Error |   StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------- |----------- |-------------- |--------------------- |--------------------- |---------:|---------:|---------:|------:|--------:|-------:|------:|------:|----------:|
|    **KeyMatch4** | **Job-SZGZJN** |      **.NET 4.8** | **/pare(...)d/123 [21]** | **/pare(...)r_id} [31]** | **19.03 μs** | **1.018 μs** | **0.673 μs** |  **1.19** |    **0.04** | **3.4180** |     **-** |     **-** |  **10.52 KB** |
|    KeyMatch4 | Job-ZPYDIF | .NET Core 3.1 | /pare(...)d/123 [21] | /pare(...)r_id} [31] | 16.05 μs | 0.549 μs | 0.363 μs |  1.00 |    0.00 | 2.7161 |     - |     - |   8.37 KB |
|              | …
> Improve KeyMatch4 function performence

- .github/workflows/github-actions-release.yml
[Github package registry not compatible with dotnet nuget client](https://github.community/t/github-package-registry-not-compatible-with-dotnet-nuget-client/14392)
[Use GitHub actions to publish NuGet packages](https://lukelowrey.com/use-github-actions-to-publish-nuget-packages/)
> Fix the error when push package to nuget.pkg.github.com in github actions fix #65

- Casbin.Benchmark/BuildInFunctionsBenchmark.cs
- NetCasbin.UnitTest/BuiltInFunctionTest.cs
- NetCasbin/Model/FunctionMap.cs
- NetCasbin/NetCasbin.csproj
- NetCasbin/Util/BuiltInFunctions.cs
- NetCasbin/Util/Function/IPMatchFunc.cs
close:  #85 
There are performance changes, The new version's `Mean` is nearly 6690% times shorter than the old version and the allocation is about 12228% times less.
```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.20201
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-preview.8.20417.9
[Host]     : .NET Core 3.1.8 (CoreCLR 4.700.20.41105, CoreFX 4.700.20.41903), X64 RyuJIT
Job-ENGJLM : .NET Framework 4.8 (4.8.4210.0), X64 RyuJIT
Job-VTJFVJ : .NET Core 3.1.8 (CoreCLR 4.700.20.41105, CoreFX 4.700.20.41903), X64 RyuJIT
IterationCount=10  RunStrategy=Throughput  
```
Old :
|  Method |        Job |       Runtime |          key1 |           key2 |     Mean |    Error |   StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated | …
> Fix IPMatch error and improve performance of it

- Casbin.Benchmark/EnforcerBenchmark.cs
- Casbin.Benchmark/TestResource.cs
- Casbin.Benchmark/examples/abac_model.conf
- NetCasbin.UnitTest/ModelTest.cs
- NetCasbin/Abstractions/IChainEffector.cs
- NetCasbin/Abstractions/IExpressionHandler.cs
- NetCasbin/Abstractions/IExpresstionCreator.cs
- NetCasbin/CoreEnforcer.cs
- NetCasbin/Effect/DefaultEffector.cs
- NetCasbin/Effect/Effect.cs
- NetCasbin/Effect/IEffector.cs
- NetCasbin/Effect/PolicyEffectType.cs
- NetCasbin/Evaluation/EffiectEvaluation.cs
- NetCasbin/Evaluation/ExpressionHandler.cs
- NetCasbin/Evaluation/IExpressionProvider.cs
- NetCasbin/InternalEnforcer.cs
- NetCasbin/ManagementEnforcer.cs
- NetCasbin/Model/Assertion.cs
- NetCasbin/Model/Model.cs
close #92  and split from #90 
The purpose of these changes almost all is to reduce allocation.
At the old version, call the enforce method once it will allocate three arrays (matches, effects, parameters),  many repeated operations (like equal the effect expression). When RBAC It will repeat allocate enumerator at RoleManger.
These some works to resolve them:
1. for equal the effect expression, It will parse once at first and use type (enum) to pass.
2. for arrays of match and effect. Now it uses the `IChainEffector` (like the stream implement of casbin v3) to evaluate the result at every policy rule. The reason to do not use the "Stream" is this work has another semantic in .NET, it does not adapt this case. And the `IChainEffector` and `EffiectEvaluation` can gain more extendable later …
> Improve performance and reduce the allocate when enforcing

- NetCasbin/InternalEnforcer.cs
- NetCasbin/Model/Assertion.cs
- NetCasbin/Model/Policy.cs
- NetCasbin/PolicyOperation.cs
Fix: https://github.com/casbin/Casbin.NET/issues/82
> feat: Support build Incremental role links

- NetCasbin.UnitTest/Fixtures/TestModelFixture.cs
- NetCasbin.UnitTest/ModelTest.cs
- NetCasbin.UnitTest/NetCasbin.UnitTest.csproj
- NetCasbin.UnitTest/Util/TestUtil.cs
- NetCasbin.UnitTest/examples/priority_explicit_deny_override_model.conf
- NetCasbin.UnitTest/examples/priority_explicit_deny_override_policy.csv
- NetCasbin/CoreEnforcer.cs
- NetCasbin/Effect/DefaultEffector.cs
- NetCasbin/Effect/PolicyEffectType.cs
- NetCasbin/Evaluation/EffiectEvaluation.cs
- NetCasbin/Model/PermConstants.cs
This PR adds support for a new PolicyEffect - PriorityDenyOverride.
It allows having multiple groups with explicit priority rank to be assigned to the same entity.
Please refer to https://github.com/casbin/Casbin.NET/issues/188 for the details and detailed issue description.
> feat: Support priority deny override model

- NetCasbin.UnitTest/ModelTest.cs
- NetCasbin/CoreEnforcer.cs
> perf: Support priority deny override model without recursion

- NetCasbin/Abstractions/IChainEffector.cs
- NetCasbin/CoreEnforcer.cs
- NetCasbin/Effect/DefaultEffector.cs
I've noticed that performance is very poor for policy files containing 10k+ policies, even when trying to enforce highest priority level policies.
It turned out, that we cannot rely on **nowEffect is not Effect.Effect.Indeterminate** check, as in some policy file versions it will never recover from **Indeterminate** status.
Easiest way how to reproduce a performance issue I'm talking about is:
**1. to replace policies of priority_explicit_deny_override_policy.csv**
```csv
p, 1, my_sub,my_obj,my_act_read,allow
p, 1, my_sub,my_obj,my_act_write,allow
p, 2, my_sub2,my_obj2,my_act_read2,allow
p, 2, my_sub2,my_obj2,my_act_write2,allow
g, alice, my_sub
```
**2. Add following test**
```c#
public void TestPriorityExplicitDenyOverrideModel()
{
var e = new …
```
> perf: resolve issue when for priority-deny-override mode, all policies were scanned, even if effect was found on higher priority levels

- NetCasbin/Abstractions/Evaluation/IExpressionCache.cs
- NetCasbin/Abstractions/Evaluation/IExpressionHandler.cs
- NetCasbin/CoreEnforcer.cs
- NetCasbin/Evaluation/ExpressionCache.cs
- NetCasbin/Evaluation/ExpressionHandler.cs
close #175 and #196
This PR can greatly improve performance (**70%** faster, and **75%** lower allocation) in most cases.
Some test results on Github Actions.
**New:**
``` ini
BenchmarkDotNet=v0.13.0, OS=Windows 10.0.17763.2061 (1809/October2018Update/Redstone5)
Intel Xeon CPU E5-2673 v4 2.30GHz, 1 CPU, 2 logical and 2 physical cores
.NET SDK=6.0.100-preview.5.21302.13
[Host]     : .NET 5.0.9 (5.0.921.35908), X64 RyuJIT
Job-BHRCLC : .NET 5.0.9 (5.0.921.35908), X64 RyuJIT
Job-ULIOOO : .NET 6.0.0 (6.0.21.30105), X64 RyuJIT
Job-JEDSDX : .NET Core 3.1.18 (CoreCLR 4.700.21.35901, CoreFX 4.700.21.36305), X64 RyuJIT
Job-QYLRWD : .NET Framework 4.8 (4.8.4400.0), X64 RyuJIT
IterationCount=10  RunStrategy=Throughput  
```
|                     Method |        Job |            Runtime | …
> feat: Support lambda expression compile and delegate cache 

- NetCasbin.UnitTest/BuiltInFunctionTest.cs
- NetCasbin/Model/FunctionMap.cs
- NetCasbin/NetCasbin.csproj
- NetCasbin/Util/BuiltInFunctions.cs
- NetCasbin/Util/Function/GlobMatchFunc.cs
Fix: https://github.com/casbin/Casbin.NET/issues/231
Implemented as a global built-in function and added related unit tests.
> feat: Add globMatch as a global built-in matcher function

- .github/workflows/sonar.yml
This PR is supposed to fix the sonarcloud analysis that is failing when the PR is opened by someone who can't read the repo secrets
> ci: fixing sonarcloud targeted analysis

- Casbin.UnitTest/UtilTests/BuiltInFunctionTest.cs
- Casbin/Model/FunctionMap.cs
- Casbin/Util/BuiltInFunctions.cs
Fix: #255 
Add KeyMatch5 to ignoring params in URL when matching keys.
Related Issue: #255 
Add a new operation keyMatch5
> feat: Add keymatch5 for ignoring params in url

- Casbin.UnitTest/Casbin.UnitTests.csproj
- Casbin.UnitTest/Fixtures/TestModelFixture.cs
- Casbin.UnitTest/ModelTests/EnforcerTest.cs
- Casbin.UnitTest/examples/subject_priority_model.conf
- Casbin.UnitTest/examples/subject_priority_model_with_domain.conf
- Casbin.UnitTest/examples/subject_priority_policy.csv
- Casbin.UnitTest/examples/subject_priority_policy_with_domain.csv
- Casbin/Abstractions/Model/IModel.cs
- Casbin/Effect/DefaultEffector.cs
- Casbin/Effect/EffectExpressionType.cs
- Casbin/Enforcer.cs
- Casbin/Evaluation/EffiectEvaluation.cs
- Casbin/Extensions/Enforcer/EnforcerExtension.cs
- Casbin/Model/Assertion.cs
- Casbin/Model/DefaultModel.cs
- Casbin/PermConstants.cs
Fix: https://github.com/casbin/Casbin.NET/issues/238
It sync the feature of golang version which is described [here](https://github.com/casbin/casbin/issues/831).
It add a new EffectType named "PriorityAllOverride" and some new methods. The way of implementation needs to be optimized.
> feat: Add priority sort with subject hierarchy.

- Casbin.UnitTest/ModelTests/ManagementApiTest.cs
- Casbin.UnitTest/SyncedModelTests/SyncedManagementApiTest.cs
- Casbin/Abstractions/Model/IModel.cs
- Casbin/Abstractions/Model/IPolicyManager.cs
- Casbin/Abstractions/Model/IPolicyStore.cs
- Casbin/Abstractions/Persist/IBatchAdapter.cs
- Casbin/Abstractions/Persist/ISingleAdapter.cs
- Casbin/Extensions/Enforcer/InternalEnforcerExtension.cs
- Casbin/Extensions/Enforcer/ManagementEnforcerExtension.cs
- Casbin/Model/Assertion.cs
- Casbin/Model/DefaultModel.cs
- Casbin/Model/DefaultPolicyManager.cs
- Casbin/Model/DefaultPolicyStore.cs
- Casbin/Model/ReaderWriterPolicyManager.cs
- Casbin/PolicyOperation.cs
Fix: #182 
In addition, several new unit tests are also added, such as verifying return values, which Golang version seems not to cover. I've tried them with the Golang version and the results are basically the same.
> feat: Add UpdatePolicy and UpdatePolicies APIs

- Casbin.UnitTests/UtilTests/BuiltInFunctionTest.cs
- Casbin/Model/FunctionMap.cs
- Casbin/Util/BuiltInFunctions.cs
Add ```keyGet``` function and related test.
> feat: Add keyGet function and related test.

- Casbin.UnitTests/ModelTests/EnforcerTest.cs
- Casbin.UnitTests/Util/TestUtil.cs
- Casbin/Abstractions/IEnforcer.cs
- Casbin/Enforcer.cs
- Casbin/Extensions/Enforcer/EnforceExtension.BatchEnforce.cs
Support batch enforce and add corresponding test. #166 
It used async stream to implement ```BatchEnforceAsync``` except ```NET452```.
It added ```BatchEnforceParallel``` in ```Enforcer``` without a corresponding interface in ```IEnforcer```. I'm not sure about the design here. What I think is that its only a special implementation so that adding it to ```IEnforcer``` may mean little.
As for the extension, I only provide methods which accept generic type inherited from ```IRequestValues```. The reason is that if I provide similar API with that of ```EnforceExtension.GenericEnforce```, users need to pass several ```IEnumerable```, such as ```e.BatchEnforce(List<T1>, List<T2>, List<T3>)```. Thus, consistency of the parameters is not actually ensured, which I think may not be a good …
> feat: Support batch enforce and add corresponding test.

- Casbin/Caching/GFunctionCache.cs
fix #296 : Concurrent error caused by GFunctionCache.
> fix: Concurrent error caused by GFunctionCache.

- Casbin.UnitTests/ModelTests/EnforcerTest.cs
- Casbin/Abstractions/IEnforcer.cs
- Casbin/DefaultEnforcer.cs
- Casbin/Enforcer.cs
- Casbin/Extensions/Enforcer/EnforcerExtension.cs
- Casbin/Extensions/Enforcer/InternalEnforcerExtension.Events.cs
Change lazyLoadPolicy to AutoLoadPolicy to avoid ignore the filter when using filtered adapter. (partially solve #288 ).
Besides, it integrates the options into ```Enforcer.Options```.
> feat: change lazyLoadPolicy to AutoLoadPolicy.

- Casbin.UnitTests/Casbin.UnitTests.csproj
- Casbin.UnitTests/Fixtures/TestModelFixture.cs
- Casbin.UnitTests/ModelTests/ModelTest.cs
- Casbin.UnitTests/examples/backslash_feed_model.conf
- Casbin.UnitTests/examples/backslash_feed_policy.csv
- Casbin/Config/DefaultConfig.cs
Support multi-line mode with '\\' line feeds and fix two improperly named variables
> feat: Support multi-line mode with '\' line feeds

- Casbin/Casbin.csproj
- README.md
Fix: https://github.com/casbin/Casbin.NET/issues/167
For the first problem, I changed the image link sources from *casbin.org* and *hsluoyz.github.io* to their respective corresponding github repositories to make the domains trusted by nuget.
For the second problem, as mentioned at [guide](https://github.com/xoofx/markdig/blob/master/src/Markdig.Tests/Specs/AutoLinks.md), I added `<p>` tags outside of the `<a>` tags to try to make the html syntax work. If it doesn't take effect, I will try instead to use `[! [PIC_NAME](PIC_URL)](LINKED_URL)` syntax. I looked through other packages on nuget and this syntax seems to be more widely used.
> feat: Add README to nuget

- Casbin.UnitTests/ModelTests/ModelTest.cs
- Casbin/Model/Request.cs
Since the key was created without adding a separator, it was possible to have illegitimate access to the cache by way of collocation. This is now fixed with reference to the go language version.
However, in order to solve this problem at all, I think it should be explicitly mentioned in the documentation that fields should not contain '$'; or the separator should be replaced with a hash value (string hash) associated with the field.
> fix: Accidental cache read via key construction

- Casbin/Casbin.csproj
- Casbin/Config/DefaultConfig.cs
Since the library can't handle newlines and comments, the ParseStringInit method processes the string first and then feeds it into ParseBuffer. in addition, since the library doesn't support net452, it retains the old parse method.
Fix: https://github.com/casbin/Casbin.NET/issues/264
> feat: Change to Microsoft.Extensions.Configuration.Ini resolution .conf

- Casbin/Extensions/Enforcer/EnforcerExtension.cs
The IEnforcer did not have the `AddMatchingFunc`, `AddDomainMatchingFunc`, `AddNamedMatchingFunc`, or `AddNamedDomainMatchingFunc` in its interface. These are also returning the enforcer which isn't consistent with the Go implementation and seems unnecessary unless you are looking to chain the funcs.
> feat: Add Matching Funcs to IEnforcer interface

- Casbin.UnitTests/Util/TestUtil.cs
- Casbin/Extensions/Enforcer/EnforcerExtension.cs
- Casbin/Extensions/Enforcer/InternalEnforcerExtension.cs
- Casbin/Extensions/Enforcer/RbacEnforcerExtension.cs
- Casbin/Extensions/Model/ModelExtension.cs
- Casbin/Extensions/Rbac/RoleManagerExtension.cs
The extension function to add a domain matching func was calling the wrong role manager method.  This resolves the issue. I also fixed a spelling error from `Manger` -> `Manager` across the repo
> feat: fix call to AddDomainMatchingFunc()

- Casbin/Extensions/Enforcer/InternalEnforcerExtension.cs
> fix: add lacked existing policy check when adding policy

- Casbin/Rbac/DefaultRoleManager.cs
Attempt at addressing #351 
Effectively causes each role in each domain to be considered their own role. 
That is:
```
g, role1, base-role, dom/*
g, alice, role1, dom/1
```
Should result in following link chain: alice in dom/1 -> role1 in dom/1 -> role1 in dom/* -> base-role in dom/*
This could lead to maximum hierarchy being reached faster then expected in some cases.
Performance and concurrency has been considered but not really tested.
Fix: https://github.com/casbin/Casbin.NET/issues/351
> feat: fix different ways of building role links when domain patterns are enabled

- Casbin.UnitTests/Fixtures/TestModelFixture.cs
- Casbin.UnitTests/ModelTests/ModelTest.cs
- Casbin.UnitTests/examples/rbac_with_index_matcher_model.conf
- Casbin.UnitTests/examples/rbac_with_index_matcher_policy.csv
- Casbin/EnforceView.cs
> fix: can not parse index operator in matcher

- Casbin.UnitTests/Fixtures/TestModelFixture.cs
- Casbin.UnitTests/ModelTests/ManagementApiTest.cs
- Casbin.UnitTests/examples/saa_model.conf
- Casbin.UnitTests/examples/saa_rbac_policy.csv
- Casbin/Model/DefaultPolicyStore.Node.cs
Came across issues that are similar to https://github.com/casbin/Casbin.NET/issues/336
Was able to create a concurrent update of the grouping policy which would trigger concurrent access errors.  It would work OK with only 100, but once you hit 500 or greater it would fail almost 100% of the time.
I don't think this should go into `master` as-is, but one of your members can take what is here and make the appropriate changes to handle the access.  You can remove my code changes and just use the test and models to see the test fail.
> fix: concurrent access issues with HashSet<string>

- Casbin/Enforcer.Internal.cs
- global.json
Fixes: #346 
The policy node lock may not unlock when exception when enforce.
> fix: Interrupt policy scanner at final block

- Casbin.UnitTests/ModelTests/RbacApiTest.cs
- Casbin.UnitTests/Util/TestUtil.cs
- Casbin/Rbac/Role.cs
> feat: support concurrent roles

- .github/workflows/build.yml
- .github/workflows/infersharp.yml
- .github/workflows/release.yml
- .github/workflows/semantic.yml
> chore: update CI jobs version

- .github/workflows/build.yml
- .github/workflows/release.yml
> chore: add setup Node.js to CI jobs
